{
    "sync.gist": "8f83ce108385226bb6dfdgdsd45357883d06fd51",
    //"terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
    "terminal.integrated.shell.windows": "G:\\program files\\Git\\bin\\bash.exe",

    "settingsSync.ignoredExtensions": [

    ],
    "settingsSync.keybindingsPerPlatform": true,
    "settingsSync.ignoredSettings": [

    ],
    "files.autoSave": "onFocusChange",
    "terminal.integrated.automationShell.windows": "",
    "tabnine.experimentalAutoImports": true,
    "workbench.colorTheme": "Learn with Sumit - Peace of the eye - Dracula version",
    "editor.codeLensFontSize": 30,
    "editor.fontSize": 18,
    "editor.fontFamily": "Fira Code",
    "editor.minimap.enabled": false,
    "task.slowProviderWarning": null,
    "editor.fontLigatures": true,
    "workbench.startupEditor": "welcomePage",
    "code-runner.clearPreviousOutput": true,
    "terminal.integrated.shell.osx": "",
    "editor.codeActionsOnSave": null,
    "terminal.integrated.automationShell.linux": "",
    "code-runner.runInTerminal": true,
    "code-runner.saveAllFilesBeforeRun": true,
    "code-runner.saveFileBeforeRun": true,
    "code-runner.terminalRoot": "/",
    "code-runner.defaultLanguage": "c",
    "code-runner.executorMap": {
        "javascript": "node",
        "java": "cd $dir && javac $fileName && java $fileNameWithoutExt",
        "c": "cd $dirWithoutTrailingSlash && gcc -std=c11 $fileName -o $fileNameWithoutExt && ./$fileNameWithoutExt",
        "cpp": "cd $dirWithoutTrailingSlash && g++ -std=c++11 $fileName -o $fileNameWithoutExt && ./$fileNameWithoutExt",
        "objective-c": "cd $dir && gcc -framework Cocoa $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
        "php": "php",
        "python": "python -u",
        "perl": "perl",
        "perl6": "perl6",
        "ruby": "ruby",
        "go": "go run",
        "lua": "lua",
        "groovy": "groovy",
        "powershell": "powershell -ExecutionPolicy ByPass -File",
        "bat": "cmd /c",
        "shellscript": "bash",
        "fsharp": "fsi",
        "csharp": "scriptcs",
        "vbscript": "cscript //Nologo",
        "typescript": "ts-node",
        "coffeescript": "coffee",
        "scala": "scala",
        "swift": "swift",
        "julia": "julia",
        "crystal": "crystal",
        "ocaml": "ocaml",
        "r": "Rscript",
        "applescript": "osascript",
        "clojure": "lein exec",
        "haxe": "haxe --cwd $dirWithoutTrailingSlash --run $fileNameWithoutExt",
        "rust": "cd $dir && rustc $fileName && $dir$fileNameWithoutExt",
        "racket": "racket",
        "scheme": "csi -script",
        "ahk": "autohotkey",
        "autoit": "autoit3",
        "dart": "dart",
        "pascal": "cd $dir && fpc $fileName && $dir$fileNameWithoutExt",
        "d": "cd $dir && dmd $fileName && $dir$fileNameWithoutExt",
        "haskell": "runhaskell",
        "nim": "nim compile --verbosity:0 --hints:off --run",
        "lisp": "sbcl --script",
        "kit": "kitc --run",
        "v": "v run",
        "sass": "sass --style expanded",
        "scss": "scss --style expanded",
        "less": "cd $dir && lessc $fileName $fileNameWithoutExt.css",
        "FortranFreeForm": "cd $dir && gfortran $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
        "fortran-modern": "cd $dir && gfortran $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
        "fortran_fixed-form": "cd $dir && gfortran $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
        "fortran": "cd $dir && gfortran $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt"
    },
    "code-runner.executorMapByGlob": {
        "c": "cd $dir && gcc $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
        "pom.xml": "cd $dir && mvn clean package"
    },
    "code-runner.fileDirectoryAsCwd": true,
    "code-runner.ignoreSelection": true,
    "code-runner.languageIdToFileExtensionMap": {
        "c":".c",
        "bat": ".bat",
        "powershell": ".ps1",
        "typescript": ".ts",
        "javascript": ".js"
    },
    "code-runner.temporaryFileName": "",
    "window.zoomLevel": -1,
    "workbench.iconTheme": "vscode-great-icons",
}